In [1]:
import pennylane as qml
from pennylane import numpy as np

In [2]:
#!pip install pennylane

In [3]:
dev = qml.device("default.qubit", wires = 2)

@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    qml.CNOT([0, 1])
    
    return qml.state()

In [4]:
print(circuit())

[0.70710678+0.j 0.        +0.j 0.        +0.j 0.70710678+0.j]


In [5]:
@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    qml.CNOT([0, 1])
    
    return qml.density_matrix(wires = range(2))

In [6]:
print(circuit())

[[0.5+0.j 0. +0.j 0. +0.j 0.5+0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]
 [0.5+0.j 0. +0.j 0. +0.j 0.5+0.j]]


In [7]:
@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    qml.CNOT([0, 1])
    
    return qml.density_matrix(wires = 0)

In [8]:
print(circuit())

[[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]


In [9]:
@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    qml.CNOT([0, 1])
    
    return qml.probs(wires = range(2))

In [10]:
print(circuit())

[0.5 0.  0.  0.5]


In [11]:
@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    qml.CNOT([0, 1])
    
    return qml.probs(wires = 0)

In [12]:
print(circuit())

[0.5 0.5]


In [13]:
@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    qml.CNOT([0, 1])
    
    return qml.probs(wires = 1)

In [14]:
print(circuit())

[0.5 0.5]


In [15]:
dev = qml.device("default.qubit", wires = 2, shots = 5)

@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    qml.CNOT([0, 1])
    
    return qml.sample()

In [16]:
print(circuit())

[[1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]]


In [17]:
dev = qml.device("default.qubit", wires = 2, shots = 5)

@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    qml.CNOT([0, 1])
    
    return qml.counts()

In [18]:
print(circuit())

{'00': tensor(4, dtype=int64, requires_grad=True), '11': tensor(1, dtype=int64, requires_grad=True)}


In [19]:
dev = qml.device("default.qubit", wires = 2, shots = 1000)

@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    qml.CNOT([0, 1])
    
    return qml.probs(wires = range(2))

In [20]:
print(circuit())

[0.492 0.    0.    0.508]


In [21]:
dev = qml.device("default.qubit", wires = 2)

@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    qml.CNOT([0, 1])
    
    return qml.expval(qml.PauliZ(0))

In [22]:
print(circuit())

0.0


In [23]:
dev = qml.device("default.qubit", wires = 2, shots = 5)

@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    qml.CNOT([0, 1])
    
    return qml.expval(qml.PauliZ(0))

In [24]:
print(circuit())

-0.2


In [25]:
dev = qml.device("default.qubit", wires = 2, shots = 5)

@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    qml.CNOT([0, 1])
    
    return qml.sample(qml.PauliZ(0))

In [26]:
results = circuit()
print(results)

[ 1.  1. -1. -1. -1.]


In [27]:
dev = qml.device("default.qubit", wires = 2, shots = [5, 50, 100, 500, 1000])

@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    qml.CNOT([0, 1])
    
    return qml.expval(qml.PauliZ(0))

In [28]:
results = circuit()
print(results)

(tensor(-0.2, requires_grad=True), tensor(-0.12, requires_grad=True), tensor(0.16, requires_grad=True), tensor(0.048, requires_grad=True), tensor(0.046, requires_grad=True))
